[package]
name = "hash"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.17", features = ["derive"] }
glob = "0.3.1"
md-5 = "0.10.6"
sha256 = "1.5.0"
